const express=require("express");const path=require("path");const Database=require("better-sqlite3");const crypto=require("crypto");const PORT=process.env.PORT||3000;const DB_PATH=process.env.DB_PATH||path.join(__dirname,"data","bitbooks.db");const fs=require("fs");fs.mkdirSync(path.dirname(DB_PATH),{recursive:true});const db=new Database(DB_PATH);db.pragma("journal_mode=WAL");
db.exec(`
CREATE TABLE IF NOT EXISTS resources(id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT NOT NULL,location TEXT NOT NULL,capacity INTEGER NOT NULL,approval INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,resourceId TEXT NOT NULL,userName TEXT NOT NULL,userId TEXT,date TEXT NOT NULL,start TEXT NOT NULL,end TEXT NOT NULL,purpose TEXT NOT NULL,status TEXT NOT NULL,createdAt INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,passwordHash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'student',createdAt INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId TEXT NOT NULL,expiresAt INTEGER NOT NULL);
`);
if(!db.prepare("PRAGMA table_info(bookings)").all().some(x=>x.name==="userId"))db.exec("ALTER TABLE bookings ADD COLUMN userId TEXT");function uid(){return crypto.randomBytes(16).toString("hex")}function hashPassword(p){const salt=crypto.randomBytes(16).toString("hex");const hash=crypto.scryptSync(p,salt,64).toString("hex");return salt+":"+hash}function verifyPassword(p,stored){try{const [salt,key]=stored.split(":");const hash=crypto.scryptSync(p,salt,64);return crypto.timingSafeEqual(hash,Buffer.from(key,"hex"))}catch{return false}}
function seedIfEmpty(){const count=db.prepare("SELECT COUNT(*) n FROM resources").get().n;if(count===0){const resources=[["Hall A — Lecture Theatre","Classroom","Main Block, Ground Floor",120,0],["Room 214","Classroom","Arts Building, 2nd Floor",40,0],["Robotics Lab","Laboratory","Engineering Wing, 1st Floor",20,1],["Chemistry Lab B","Laboratory","Science Block, 2nd Floor",24,1],["Seminar Room 3","Seminar Room","Library, 3rd Floor",15,0],["Auditorium","Facility","Student Centre",300,1]];const ins=db.prepare("INSERT INTO resources VALUES(?,?,?,?,?,?)");resources.forEach(r=>ins.run(uid(),...r))}}
seedIfEmpty();const adminEmail=process.env.ADMIN_EMAIL||"admin@bitbooks.local",adminPassword=process.env.ADMIN_PASSWORD||"Admin@12345";if(!db.prepare("SELECT id FROM users WHERE email=?").get(adminEmail))db.prepare("INSERT INTO users(id,name,email,passwordHash,role,createdAt) VALUES(?,?,?,?,?,?)").run(uid(),"Campus Administrator",adminEmail,hashPassword(adminPassword),"admin",Date.now());
const app=express();app.use(express.json());app.use((req,res,next)=>{const token=(req.headers.cookie||"").match(/bitbooks_session=([^;]+)/)?.[1];if(token){const s=db.prepare("SELECT * FROM sessions WHERE token=? AND expiresAt>?").get(token,Date.now());if(s)req.user=db.prepare("SELECT id,name,email,role FROM users WHERE id=?").get(s.userId)}next()});
function requireLogin(req,res,next){if(!req.user)return res.status(401).json({error:"Please sign in first"});next()}function requireAdmin(req,res,next){if(!req.user||req.user.role!=="admin")return res.status(403).json({error:"Admin access required"});next()}
app.post("/api/auth/register",(req,res)=>{const {name,email,password}=req.body||{};if(!name||!email||!password||password.length<6)return res.status(400).json({error:"Name, email and a password of at least 6 characters are required"});const clean=String(email).trim().toLowerCase();try{const id=uid();db.prepare("INSERT INTO users(id,name,email,passwordHash,role,createdAt) VALUES(?,?,?,?,?,?)").run(id,String(name).trim(),clean,hashPassword(password),"student",Date.now());const token=uid()+uid();db.prepare("INSERT INTO sessions VALUES(?,?,?)").run(token,id,Date.now()+7*86400000);res.setHeader("Set-Cookie",`bitbooks_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`);res.status(201).json({user:{id,name:String(name).trim(),email:clean,role:"student"}})}catch(e){res.status(409).json({error:"An account with that email already exists"})}});
app.post("/api/auth/login",(req,res)=>{const {email,password}=req.body||{};const u=db.prepare("SELECT * FROM users WHERE email=?").get(String(email||"").trim().toLowerCase());if(!u||!verifyPassword(String(password||""),u.passwordHash))return res.status(401).json({error:"Incorrect email or password"});const token=uid()+uid();db.prepare("INSERT INTO sessions VALUES(?,?,?)").run(token,u.id,Date.now()+7*86400000);res.setHeader("Set-Cookie",`bitbooks_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`);res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post("/api/auth/logout",(req,res)=>{const token=(req.headers.cookie||"").match(/bitbooks_session=([^;]+)/)?.[1];if(token)db.prepare("DELETE FROM sessions WHERE token=?").run(token);res.setHeader("Set-Cookie","bitbooks_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0");res.json({ok:true})});
app.get("/api/auth/me",(req,res)=>res.json({user:req.user||null}));
function conflict(resourceId,date,start,end,exclude){const rows=db.prepare("SELECT * FROM bookings WHERE resourceId=? AND date=? AND status IN ('pending','confirmed') AND id!=?").all(resourceId,date,exclude||"");return rows.find(b=>start<b.end&&b.start<end)}
app.get("/api/resources",(req,res)=>res.json(db.prepare("SELECT * FROM resources ORDER BY name").all().map(r=>({...r,approval:!!r.approval}))));
app.post("/api/resources",requireAdmin,(req,res)=>{const {name,type,location,capacity,approval}=req.body||{};if(!name||!type||!location||!capacity)return res.status(400).json({error:"All resource fields are required"});const row={id:uid(),name:String(name).trim(),type,location:String(location).trim(),capacity:parseInt(capacity,10),approval:approval?1:0};db.prepare("INSERT INTO resources VALUES(@id,@name,@type,@location,@capacity,@approval)").run(row);res.status(201).json({...row,approval:!!row.approval})});
app.delete("/api/resources/:id",requireAdmin,(req,res)=>{const x=db.prepare("DELETE FROM resources WHERE id=?").run(req.params.id);if(!x.changes)return res.status(404).json({error:"Resource not found"});res.status(204).end()});
app.get("/api/bookings",requireLogin,(req,res)=>{const rows=req.user.role==="admin"?db.prepare("SELECT * FROM bookings ORDER BY createdAt DESC").all():db.prepare("SELECT * FROM bookings WHERE userId=? OR userId IS NULL AND userName=? ORDER BY createdAt DESC").all(req.user.id,req.user.name);res.json(rows)});
app.get("/api/bookings/check-conflict",requireLogin,(req,res)=>{const {resourceId,date,start,end,excludeId}=req.query;if(!resourceId||!date||!start||!end)return res.status(400).json({error:"Missing booking details"});const x=conflict(resourceId,date,start,end,excludeId);res.json({conflict:x||null})});
app.post("/api/bookings",requireLogin,(req,res)=>{const {resourceId,date,start,end,purpose}=req.body||{};if(!resourceId||!date||!start||!end||!purpose)return res.status(400).json({error:"All booking fields are required"});if(end<=start)return res.status(400).json({error:"End time must be after start time"});const r=db.prepare("SELECT * FROM resources WHERE id=?").get(resourceId);if(!r)return res.status(404).json({error:"Resource not found"});const x=conflict(resourceId,date,start,end);if(x)return res.status(409).json({error:"That slot is already booked",conflict:x});const b={id:uid(),resourceId,userName:req.user.name,userId:req.user.id,date,start,end,purpose:String(purpose).trim(),status:r.approval?"pending":"confirmed",createdAt:Date.now()};db.prepare("INSERT INTO bookings VALUES(@id,@resourceId,@userName,@userId,@date,@start,@end,@purpose,@status,@createdAt)").run(b);res.status(201).json(b)});
function transition(req,res,from,to){const b=db.prepare("SELECT * FROM bookings WHERE id=?").get(req.params.id);if(!b)return res.status(404).json({error:"Booking not found"});if(!from.includes(b.status))return res.status(409).json({error:"Invalid booking status"});if(req.user.role!=="admin"&&b.userId!==req.user.id)return res.status(403).json({error:"You can only manage your own bookings"});db.prepare("UPDATE bookings SET status=? WHERE id=?").run(to,b.id);res.json({...b,status:to})}
app.post("/api/bookings/:id/cancel",requireLogin,(req,res)=>transition(req,res,["pending","confirmed"],"cancelled"));
app.post("/api/bookings/:id/approve",requireAdmin,(req,res)=>transition(req,res,["pending"],"confirmed"));
app.post("/api/bookings/:id/reject",requireAdmin,(req,res)=>transition(req,res,["pending"],"rejected"));
app.post("/api/bookings/:id/complete",requireAdmin,(req,res)=>transition(req,res,["confirmed"],"completed"));
app.get("/api/health",(req,res)=>res.json({ok:true}));
app.use(express.static(path.join(__dirname,"public")));app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("Bit Books server listening on "+PORT));
